#cd /mnt/c/entwicklung/ansible/openhab && ansible-playbook -i hosts config.yml --ask-pass --ask-become-pass --user openhabian
- name: checkout python scripts
  hosts: openhabian
  become: true
  remote_user: openhabian
  
  vars:
   home_dir: "/home/openhabian"
   
  
  tasks:
   - git:
      repo: 'https://github.com/AndreasD83/ultraschall'
      dest: /home/openhabian/ultraschall
      force: yes
   - name: Create directory 
     file:
        path: /etc/ultraschall
        state: directory
   - name: install module requests
     become: yes
     shell:
         pip install requests
   - name: install module pika
     become: yes
     shell:
         pip install pika
   - name: mv python ultraschallsensor_entfernung.py
     become: yes
     shell:
         mv /home/openhabian/ultraschall/ultraschallsensor_entfernung.py /etc/ultraschall/