##cd /mnt/c/entwicklung/ansible/openhab && ansible-playbook -i hosts rabbitmq.yml --ask-pass --ask-become-pass --user openhabian
- hosts: openhabian
  become: true
  become_method: sudo
  remote_user: openhabian
  vars:
    rabbitmq_version: 3.0.2-1

  tasks:
  - name: add repo key rabbit
    become: yes
    shell: 
      wget -O- https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc | sudo apt-key add -
  - name: add trusted key
    apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present
  - name: add repo rabbit
    become: yes
    shell: 
      echo "deb https://dl.bintray.com/rabbitmq/debian $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/rabbitmq.list
  - name: install rabbitmq-server
    apt: name={{ item }} state=present
    with_items:
      - rabbitmq-server

  - name: enable rabbitmq plugins
    rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled
    notify:
    - restart rabbitmq

  - name: add users
    rabbitmq_user: user={{item.username}} password={{item.password}} tags=administrator,{{item.username}} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present
    with_items:
    - { username: writer, password: writer }
    - { username: reader, password: reader }
    - { username: ultra, password: ultra }

  - name: remove default guest user
    rabbitmq_user: user=guest state=absent
  - rabbitmq_queue:
      name: ultrasonicQueue
      login_user: ultra
      login_password: ultra
      login_host: openhabianpi
  - rabbitmq_queue:
      name: wrongValueQueue
      login_user: ultra
      login_password: ultra
      login_host: openhabianpi
  - rabbitmq_exchange:
      name: inbound
      login_user: ultra
      login_password: ultra
      login_host: openhabianpi
  - rabbitmq_binding:
     name: inbound
     destination: ultrasonicQueue
     type: queue
     routing_key: difference
     login_user: ultra
     login_password: ultra
     login_host: openhabianpi
  - rabbitmq_binding:
     name: inbound
     destination: wrongValueQueue
     type: queue
     routing_key: wrong_value
     login_user: ultra
     login_password: ultra
     login_host: openhabianpi
  - name: ensure vhost /test is present
    rabbitmq_vhost: name=/test state=present
      
  
    
  handlers:
  - name: restart rabbitmq
    service: name=rabbitmq-server state=restarted