##cd /mnt/c/entwicklung/ansible/openhab && ansible-playbook -i hosts rabbitmq.yml --ask-pass --ask-become-pass --user openhabian
- hosts: openhabian
  become: true
  become_method: sudo
  vars:
    rabbitmq_version: 3.0.2-1

  tasks:
  - name: ensure software-properties-common is installed
    apt: pkg=software-properties-common state=installed

  - name: add rabbitmq official apt repository
    apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

  - name: add trusted key
    apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

  - name: install package
    apt: name={{ item }} update_cache=yes state=installed
    with_items:
      - rabbitmq-server

  - name: enable rabbitmq plugins
    rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled
    notify:
    - restart rabbitmq

  - name: add users
    rabbitmq_user: user={{item}} password=ultra tags=administrator,{{item}} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present
    with_items:
    - ultra

  - name: remove default guest user
    rabbitmq_user: user=guest state=absent

  - name: ensure vhost /test is present
    rabbitmq_vhost: name=/test state=present

  handlers:
  - name: restart rabbitmq
    service: name=rabbitmq-server state=restarted